dist: trusty
language: php
sudo: false

addons:
  chrome: stable

php:
  - 7.0

mysql:
  database: drupal
  username: root
  encoding: utf8

cache:
  yarn: true
  directories:
     - $HOME/.composer/cache
     - $HOME/.drush/cache
     - $HOME/.npm
     - campaignion_email_to_target/datasets_app/node_modules
     - campaignion_email_to_target/messages_app/node_modules
     - campaignion_wizard/redirects_app/node_modules

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:8.1.* dflydev/hawk phpunit/phpunit:6.4.* torotil/upal:1.1.3
  - nvm install 10.0.0
  - npm install -g yarn

before_script:
  - repo=`pwd`
  - root=$HOME/test-root
  - mysql -e 'create database drupal'
  - php -d include_path=`pwd` -d sendmail_path=`which true` ~/.composer/vendor/bin/drush.php --yes core-quick-drupal --core=drupal-7.x --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/drupal --root=$root
  - ln -s $repo $root/sites/all/modules/campaignion
  - cd $root
  - drush dl addressfield ctools date entity features field_type_language form_builder-7.x-2.0-alpha2 i18n little_helpers-2.0-alpha2 oowizard paypal_payment psr0 redhen references webform webform_confirm_email webform_template ultimate_cron
  - drush --yes pm-enable campaignion_test

script:
  - cd $repo
  - UPAL_ROOT=$root UPAL_WEB_URL=http://127.0.0.1 phpunit --bootstrap=$HOME/.composer/vendor/torotil/upal/bootstrap.php --coverage-clover=coverage.xml .
  - cd $repo/campaignion_email_to_target/datasets_app
  - yarn install
  - yarn unit
  - cd $repo/campaignion_email_to_target/messages_app
  - yarn install
  - yarn unit
  - cd $repo/campaignion_wizard/redirects_app
  - yarn install
  - yarn unit

after_success:
  - bash <(curl -s https://codecov.io/bash)
